---
engines:
  coverage:
    exclude_paths:
      - '**/test/**'
  duplication:
    exclude_paths:
      - '**/test/**'
  metric:
    exclude_paths:
      - '**/test/**'
languages:
  cpp:
    extensions:
      - '.h'
