name: Build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'

jobs:
  build:
    uses: mbeckh/cmake-utils/.github/workflows/run-build.yml@v1
    secrets: inherit
