name: Build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

permissions: {}

jobs:
  build:
    name: Build
    uses: mbeckh/cmake-utils/.github/workflows/run-build.yml@v1
    secrets: inherit
    permissions:
      actions: write
      contents: read
      packages: write
