# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# Find more information at:
# https://github.com/microsoft/msvc-code-analysis-action

name: Microsoft C++ Code Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '29 18 * * 2'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache vcpkg
      uses: actions/cache@v2
      with:
        path: build/Release/vcpkg_installed
        key: vcpkg_installed-Release-${{hashFiles('**/vcpkg.json', '**/vcpkg-configuration.json', '!build/**')}}

    - name: Setup MSVC Environment
      uses: mbeckh/msvc-dev-cmd@master

    - name: Configure
      uses: mbeckh/cmake-utils/configure@master
      with:
        build-root: build
        binary-dir: build/Release
        configuration: Release

    - name: Build
      shell: cmd
      working-directory: build/Release
      run: cmake --build . --target generated-sources

    - name: Initialize MSVC Code Analysis
      uses: microsoft/msvc-code-analysis-action@04825f6d9e00f87422d6bf04e1a38b1f3ed60d99
      id: run-analysis
      with:
        cmakeBuildDirectory: build/Release
        ruleset: NativeRecommendedRules.ruleset

    - name: Upload SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.run-analysis.outputs.sarif }}

    # - name: Upload SARIF as an Artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: sarif-file
    #     path: ${{ steps.run-analysis.outputs.sarif }}
