name: Microsoft C++ Code Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  schedule:
    - cron: '29 18 * * 2'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-2022
    permissions:
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache vcpkg
      uses: actions/cache@v2
      with:
        path: build/Release/vcpkg_installed
        key: vcpkg_installed-Release-${{hashFiles('**/vcpkg.json', '**/vcpkg-configuration.json', '!build/**')}}

    - name: Setup MSVC Environment
      uses: mbeckh/msvc-dev-cmd@master

    - name: Configure
      uses: mbeckh/cmake-utils/configure@master
      with:
        build-root: build
        binary-dir: build/Release
        configuration: Release
        extra-args: -D CMAKE_UNITY_BUILD:BOOL=ON -D CMAKE_DISABLE_PRECOMPILE_HEADERS:BOOL=ON -D CMU_DISABLE_DEBUG_INFORMATION:BOOL=ON

    - name: Build
      shell: cmd
      working-directory: build/Release
      run: cmake --build . --target generated-sources

    - name: Initialize MSVC Code Analysis
      uses: mbeckh/msvc-code-analysis-action@main
      id: run-analysis
      with:
        cmakeBuildDirectory: build/Release
        ruleset: NativeRecommendedRules.ruleset
        loadImplicitCompilerEnv: false

    - name: Upload SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{steps.run-analysis.outputs.sarif}}

    - name: Upload SARIF as an Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sarif-file
        path: ${{steps.run-analysis.outputs.sarif}}
